"""What this deployment can actually do - reported to the UI, never assumed."""

from __future__ import annotations

from .config import get_settings
from .db import database_state


def describe_capabilities() -> dict:
    settings = get_settings()
    config = settings.public_config()
    database = database_state()
    llm_provider = (settings.llm_provider or "none").lower()
    llm_configured = llm_provider not in {"none", ""} and bool(settings.active_llm_key())
    neural_embeddings = (settings.embeddings_provider or "local").lower() == "openai" and bool(settings.openai_api_key)

    return {
        "llm": {
            "provider": llm_provider,
            "model": settings.llm_model,
            "configured": llm_configured,
            "mode": "llm" if llm_configured else "retrieval-only",
            "note": (
                "Answers are generated by the configured LLM and grounded in retrieved repository evidence."
                if llm_configured else
                "No LLM key configured: AI Chat answers from retrieved code evidence with citations "
                "(extractive, never invented)."
            ),
        },
        "embeddings": {
            "provider": settings.embeddings_provider,
            "model": settings.embeddings_model or ("text-embedding-3-small" if neural_embeddings else None),
            "dim": settings.embedding_dim,
            "neural": neural_embeddings,
            "note": (
                "Neural embeddings via an OpenAI-compatible endpoint."
                if neural_embeddings else
                "Offline hashed embeddings: real lexical retrieval over code tokens and n-grams, "
                "not a neural semantic model."
            ),
        },
        "database": {
            "dialect": database.get("dialect", config["database"]["dialect"]),
            "pgvector": bool(database.get("pgvector")),
            "search_backend": "pgvector" if database.get("pgvector") else "in-process (SQLite fallback)",
            "location": config["database"]["location"],
            "note": (
                "Postgres with pgvector: cosine similarity search executed in the database."
                if database.get("pgvector") else
                "No pgvector available: vectors are stored as JSON and ranked in-process. "
                "Set DATABASE_URL to a Postgres+pgvector instance (e.g. Neon) for production scale."
            ),
        },
        "github": {
            "authenticated": bool(settings.github_token),
            "rate_limit": config["github"]["rate_limit"],
            "note": (
                "GitHub token configured - 5000 requests/hour."
                if settings.github_token else
                "Anonymous GitHub access - 60 requests/hour. Set GITHUB_TOKEN for larger repositories."
            ),
        },
        "limits": settings.public_config()["limits"],
    }
