"""Documentation generation.

Documents are built purely from the analysed artefacts (counts, evidence, endpoints,
workflows). Nothing is generated by an AI model, so the output is repeatable and cannot invent facts.
"""

from __future__ import annotations

import logging


logger = logging.getLogger(__name__)


def _repo_line(overview: dict) -> str:
    repo = overview.get("repo", {})
    parts = [f"**{repo.get('full_name', 'repository')}**"]
    if repo.get("description"):
        parts.append(f"- {repo['description']}")
    if repo.get("primary_language"):
        parts.append(f"- Primary language: {repo['primary_language']}")
    if repo.get("default_branch"):
        parts.append(f"- Default branch: `{repo['default_branch']}`")
    if repo.get("stars") is not None:
        parts.append(f"- Stars: {repo.get('stars')}")
    return "\n".join(parts)


def build_readme(overview: dict, architecture: dict, endpoints: list[dict], database: dict,
                 workflows: list[dict], frameworks: list[dict]) -> str:
    lines = [f"# {overview.get('repo', {}).get('full_name', 'Repository')} - architecture overview", ""]
    lines.append(_repo_line(overview))
    lines.append("")
    lines.append(f"_Generated by RepoLens from analysis `{overview.get('run', {}).get('id', '')[:10]}` "
                 f"({overview.get('files', 0)} files, {overview.get('loc', 0):,} lines of code)._")
    lines.append("")

    if frameworks:
        lines.append("## Stack")
        lines.append("")
        for framework in frameworks[:12]:
            evidence = framework.get("evidence") or []
            suffix = f" - {evidence[0]}" if evidence else ""
            lines.append(f"- **{framework['name']}** ({framework.get('ecosystem', 'n/a')},"
                         f" confidence {framework.get('confidence', 0):.0%}){suffix}")
        lines.append("")

    languages = overview.get("languages") or []
    if languages:
        lines.append("## Languages")
        lines.append("")
        lines.append("| Language | Files | LOC | Share |")
        lines.append("| --- | ---: | ---: | ---: |")
        for language in languages[:10]:
            lines.append(f"| {language['label']} | {language['files']} | {language['loc']:,} | {language['percent']}% |")
        lines.append("")

    lines.append("## Architecture")
    lines.append("")
    for layer in architecture.get("layers", []):
        lines.append(f"- **{layer['label']}** - {layer['files']} file(s), {layer['loc']:,} LOC. {layer['description']}")
    lines.append("")
    if architecture.get("edges"):
        lines.append("### Layer dependencies")
        lines.append("")
        for edge in architecture["edges"][:10]:
            lines.append(f"- `{edge['source']}` → `{edge['target']}` ({edge['weight']} reference(s),"
                         f" {', '.join(edge['kinds'])})")
        lines.append("")

    if endpoints:
        lines.append("## API surface")
        lines.append("")
        lines.append("| Method | Path | Handler | File |")
        lines.append("| --- | --- | --- | --- |")
        for endpoint in endpoints[:60]:
            handler = endpoint.get("handler") or "-"
            lines.append(f"| {endpoint['method']} | `{endpoint['path']}` | `{handler}` | `{endpoint['file_path']}:{endpoint.get('line') or '?'}` |")
        if len(endpoints) > 60:
            lines.append(f"| … | _{len(endpoints) - 60} more endpoints_ | | |")
        lines.append("")

    if database.get("models"):
        lines.append("## Data model")
        lines.append("")
        for model in database["models"][:25]:
            field_names = ", ".join(field.get("name", "?") for field in (model.get("fields") or [])[:10])
            table = model.get("table") or model["name"]
            orm = model.get("orm") or "unknown"
            lines.append(f"- **{model['name']}** (`{table}`, {orm}) at `{model['file_path']}:{model.get('line') or '?'}`")
            if field_names:
                lines.append(f"  - fields: {field_names}")
        lines.append("")
        if database.get("notes"):
            for note in database["notes"]:
                lines.append(f"> {note}")
            lines.append("")

    if workflows:
        lines.append("## Key workflows")
        lines.append("")
        for workflow in workflows[:10]:
            lines.append(f"### {workflow['name']}")
            lines.append("")
            lines.append(f"Trigger: `{workflow.get('trigger')}` · confidence {workflow.get('confidence', 0):.0%}")
            lines.append("")
            for index, step in enumerate(workflow.get("steps", []), start=1):
                location = f" - `{step['file_path']}:{step.get('line')}`" if step.get("file_path") else ""
                lines.append(f"{index}. **{step['label']}** ({step['kind']}){location}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Everything above was generated from static analysis of this repository. "
                 "RepoLens never invents files, symbols or endpoints: when something could not be determined, "
                 "the analysis says so._")
    return "\n".join(lines)


def build_api_reference(overview: dict, endpoints: list[dict]) -> str:
    lines = [f"# API reference - {overview.get('repo', {}).get('full_name', 'repository')}", ""]
    lines.append(f"{len(endpoints)} endpoint(s) discovered by static analysis. "
                 "Handlers, files and inferred services are listed for each route.")
    lines.append("")
    by_path: dict[str, list[dict]] = {}
    for endpoint in endpoints:
        by_path.setdefault(endpoint["path"], []).append(endpoint)
    for path in sorted(by_path):
        lines.append(f"## `{path}`")
        lines.append("")
        for endpoint in sorted(by_path[path], key=lambda item: item["method"]):
            lines.append(f"### {endpoint['method']}")
            lines.append("")
            lines.append(f"- Handler: `{endpoint.get('handler') or 'unknown'}`")
            lines.append(f"- Declared in: `{endpoint['file_path']}:{endpoint.get('line') or '?'}`")
            if endpoint.get("controller"):
                lines.append(f"- Controller: `{endpoint['controller']}`")
            if endpoint.get("service"):
                lines.append(f"- Calls into: `{endpoint['service']}`")
            if endpoint.get("framework"):
                lines.append(f"- Framework: {endpoint['framework']}")
            if endpoint.get("auth_required"):
                lines.append("- Authentication: an auth dependency/guard was detected")
            if endpoint.get("request_model"):
                lines.append(f"- Request model: `{endpoint['request_model']}`")
            if endpoint.get("response_model"):
                lines.append(f"- Response model: `{endpoint['response_model']}`")
            if endpoint.get("notes"):
                lines.append(f"- Notes: {endpoint['notes']}")
            lines.append("")
    return "\n".join(lines)


def build_onboarding(overview: dict, architecture: dict, endpoints: list[dict], database: dict,
                     workflows: list[dict], graph_stats: dict, quality: dict) -> str:
    repo = overview.get("repo", {})
    lines = [f"# Onboarding guide - {repo.get('full_name', 'repository')}", "",
             f"_{repo.get('description') or 'No repository description provided.'}_", "",
             "## 30-second summary", "",
             f"- {overview.get('files', 0):,} files analysed, {overview.get('loc', 0):,} lines of code, "
             f"{overview.get('symbols', 0):,} functions/classes",
             f"- {overview.get('endpoints', 0)} API endpoints, {overview.get('modules', 0)} modules, "
             f"{graph_stats.get('edges', 0)} dependency edges",
             f"- Data layer: {', '.join(tech['name'] for tech in database.get('technologies', [])[:4]) or 'not detected'}",
             f"- Quality signal: {quality.get('summary', {}).get('health_label', 'n/a')} "
             f"({quality.get('summary', {}).get('issues', 0)} heuristic findings)",
             "",
             "## Where to start reading", ""]
    entrypoints = architecture.get("entrypoints") or []
    if entrypoints:
        for entry in entrypoints[:8]:
            lines.append(f"- `{entry['path']}` - {entry['kind']} ({entry['detail']})")
    else:
        lines.append("- No obvious entrypoint was detected; start from the largest module in the dependency view.")
    lines.append("")
    lines.append("## How a request flows")
    lines.append("")
    if workflows:
        workflow = workflows[0]
        lines.append(f"Traced example - **{workflow['name']}**:")
        lines.append("")
        for index, step in enumerate(workflow.get("steps", []), start=1):
            location = f" (`{step['file_path']}:{step.get('line')}`)" if step.get("file_path") else ""
            lines.append(f"{index}. {step['label']} - {step['kind']}{location}")
    else:
        lines.append("No HTTP entrypoint was found to trace. The repository may be a library, CLI or data pipeline.")
    lines.append("")
    lines.append("## Conventions and gotchas")
    lines.append("")
    for note in architecture.get("notes", []):
        lines.append(f"- {note}")
    if graph_stats.get("cycles"):
        lines.append(f"- {graph_stats['cycles']} circular dependency group(s) detected - review before refactoring.")
    if overview.get("failed_files"):
        lines.append(f"- {overview['failed_files']} file(s) failed to parse; those areas are under-analysed.")
    lines.append("")
    lines.append("## Highest-risk modules to understand first")
    lines.append("")
    hubs = overview.get("hubs") or []
    for hub in hubs[:6]:
        lines.append(f"- `{hub['path']}` - coupling {hub['coupling']} (fan-in {hub['fan_in']}, fan-out {hub['fan_out']})")
    lines.append("")
    lines.append("_Generated by RepoLens from static analysis. Verify critical details against the code before relying on them._")
    return "\n".join(lines)


def generate_docs(kind: str, *, overview: dict, architecture: dict, endpoints: list[dict], database: dict,
                  workflows: list[dict], frameworks: list[dict], graph_stats: dict, quality: dict) -> dict:
    """Return {kind, title, markdown, generated_by}."""
    if kind == "readme":
        markdown = build_readme(overview, architecture, endpoints, database, workflows, frameworks)
        title = "Repository overview"
    elif kind == "api":
        markdown = build_api_reference(overview, endpoints)
        title = "API reference"
    elif kind == "onboarding":
        markdown = build_onboarding(overview, architecture, endpoints, database, workflows, graph_stats, quality)
        title = "Onboarding guide"
    else:
        raise ValueError(f"Unknown document kind `{kind}`. Supported: readme, api, onboarding.")

    generated_by = "deterministic analysis"
    return {"kind": kind, "title": title, "markdown": markdown, "generated_by": generated_by}
